"""Layers modified SVG layer added

Revision ID: d60249a06f20
Revises: 01977fabfb72
Create Date: 2024-01-23 12:49:00.591182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd60249a06f20'
down_revision: Union[str, None] = '01977fabfb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layer')
    op.drop_table('dwg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dwg',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dwg_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dwg_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('layer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('dwg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dwg_id'], ['dwg.id'], name='layer_dwg_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='layer_pkey')
    )
    # ### end Alembic commands ###
